name: Scrape Reddit Trends Daily

on:
  schedule:
    - cron: '0 6 * * *' # Every day at 6am UTC (change as needed)
  workflow_dispatch:    # Allow manual runs

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests pandas

      - name: Run the scraper
        run: python main.py

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add *.csv
          git commit -m "Automated data scrape: $(date -u +"%Y-%m-%d %H:%M")" || echo "No changes to commit"
          git push
        env:
          # Only needed if you use a personal access token; usually not required for pushing to same repo with GITHUB_TOKEN
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
